//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterGarden
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget_history
    {
        public int id { get; set; }
        public Nullable<int> year_plan { get; set; }
        public int number_of_people { get; set; }
        public Nullable<int> plan_income { get; set; }
        public Nullable<int> fact_income { get; set; }
    }
}
