//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterGarden
{
    using System;
    using System.Collections.Generic;
    
    public partial class cleaning_works
    {
        public int id { get; set; }
        public Nullable<int> cost { get; set; }
        public string date { get; set; }
        public string note { get; set; }
        public Nullable<int> fk { get; set; }
    
        public virtual workers workers { get; set; }
    }
}
