//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterGarden
{
    using System;
    using System.Collections.Generic;
    
    public partial class people
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string phone { get; set; }
        public string namber { get; set; }
        public string note { get; set; }
        public Nullable<int> summa { get; set; }
        public string payment_date { get; set; }
    }
}
