//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinterGarden
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WG_db : DbContext
    {
        public WG_db()
            : base("name=WG_db")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<budget_history> budget_history { get; set; }
        public virtual DbSet<cleaning_works> cleaning_works { get; set; }
        public virtual DbSet<people> people { get; set; }
        public virtual DbSet<workers> workers { get; set; }
    }
}
